### ISSUE TITLE
"Error: This is not a Drawio file!" when opening valid *.drawio-file

### ISSUE THREAD

**Issue by ETES-Stuttgart** [owncloud/drawio#21]
Hey there,

since the last update of the draw.io app (now using 1.0.0), some drawio-files (we have several ones with this exact issue) cannot be loaded in the app. When trying to open the files, we get `Error: This is not a Drawio file!`.
![grafik](https://github.com/owncloud/drawio/assets/87643186/19207da3-47e7-47fd-8a9f-46012cf9c42e)

The exact same file could be opened with the previous version of the draw.io-app, I tested that.
The file itself is valid (I checked in a XML-validator and I can open the app in the draw.io-offline-application as well as on https://app.diagrams.net/.

**Additional information**

drawio:
```
  - drawio:
    - Version: 1.0.0
    - Path: [...]/owncloud/apps/drawio
```
ownCloud:
```
  - installed: true
  - first_install_version: 10.4.1.3
  - version: 10.12.0.6
  - versionstring: 10.12.0
  - edition: Community
```
Please let me know, if you need further information to debug this issue.

Thank you in advance,
& best regards!

**Comment by DeepDiver1975** [comment]
Can you please give this patch a try?
https://github.com/owncloud/drawio/pull/19

THX
