### ISSUE TITLE
Potential data loss due to missing locking

### ISSUE THREAD

**Issue by jnweiger** [owncloud/drawio#5]
## Seen with drawio 1.0.0-rc.1 and core 10.12.1

* `occ app:enable drawio`
* User Admin shares his Documents folder with user Alice with full read/Write permisisons.
* Admin creates a `New Diagram.drawio` chosses a template and starts editing.
* User Alice visits the shared folder and clicks open on `New Diagram.drawio` .
* Admin adds one day worth of work and saves the document.
* Alice adds one simple change, and saves the document.
* The one day worth of work of Admin is lost. BAD.

### Expected behaviour
* File locking is applied while Admin has drawio open.
* Alice sees the file in readonly mode, as if the sharing were readonly.

**Comment by DeepDiver1975** [comment]
requires core patch to allow OC.File.Client.putFileContents to send the lock token ....

**Comment by mrow4a** [comment]
@DeepDiver1975 ohh ok, otherwise we would need to build custom API endpoints like for TextEditor right ? But then drawio would only be compatible with newest OC versions.

**Comment by DeepDiver1975** [comment]
I patched the necessary parts into the drawio app

**Comment by jnweiger** [comment]
Retested in 1.0.0-rc.2
Fixed. thanks.
